# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - run: docker-compose -f docker-compose-build.yaml build --parallel
    - run: docker tag reverseproxy theopen4/reverseproxy:v1
    - run: docker tag udagram-api-user theopen4/udagram-api-user:v1
    - run: docker tag udagram-api-feed theopen4/udagram-api-feed:v1
    - run: docker tag udagram-frontend theopen4/udagram-frontend:v1
    - run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - run: docker push theopen4/reverseproxy:v1
    - run: docker push theopen4/udagram-api-user:v1
    - run: docker push theopen4/udagram-api-feed:v1
    - run: docker push theopen4/udagram-frontend:v1
